### ISSUE TITLE
spring-boot-starter-amqp, traces are not being injected in logs

### ISSUE THREAD

**Issue by Jojoooo1** [spring-projects-experimental/spring-cloud-sleuth-otel#100]
**Describe the bug**
spring-boot: 2.6.3
spring-boot-starter-amqp: 2.6.3
spring-cloud.version: 2021.0.0
spring-cloud-sleuth-otel.version:1.1.0-SNAPSHOT
opentelemetry-exporter-otlp:1.10.1
grpc-netty-shaded: 1.44.0

**Sample**
Before upgrade (using only spring-cloud-sleuth):
![Screenshot from 2022-02-07 18-36-48](https://user-images.githubusercontent.com/17641873/152876129-a5591981-0b9d-420e-8619-d66e0892ff78.png)

After upgrade:
![Screenshot from 2022-02-07 13-58-07](https://user-images.githubusercontent.com/17641873/152835100-2b4c409f-f574-4bed-be5b-5d5a84f76ee4.png)

After upgrading to spring-cloud-sleuth-otel, traces are not being injected anymore.

As shown in the picture, traces are being injected in the controller `HomeController` but not in the @RabbitListener `WebhookListenerService`

**Comment by marcingrzejszczak** [comment]
Reproducer - I created a demo project here (https://github.com/codebycase/demo), you can see the README.md and run DemoApplication to test out.

**Comment by marcingrzejszczak** [comment]
Brave is working fine because it has a dedicated Spring RabbitMQ instrumentation https://github.com/openzipkin/brave/tree/master/instrumentation/spring-rabbit . We have not ported it over to the Sleuth OTel version (and we're not planning to). This is natively supported in Spring AMQP https://docs.spring.io/spring-amqp/docs/current/reference/html/#micrometer-observation with Micrometer Observation and Micrometer Tracing.
