### ISSUE TITLE
Excluding spring-cloud-sleuth-brave is not enough

### ISSUE THREAD

**Issue by nfrankel** [spring-projects-experimental/spring-cloud-sleuth-otel#119]
**Describe the bug**

The documentation (and the sample) mentions that it's enough to exclude `spring-cloud-sleuth-brave` from the `spring-cloud-starter-sleuth` dependency. If I only do it, I'm faced with:

```
org.springframework.cloud.sleuth.autoconfig.otel.MultipleTracerAutoConfigurationsDetector$MultipleTracersFoundException: You have both Spring Cloud Sleuth OpenTelemetry (OTel) and Spring Cloud Sleuth Brave tracers on the classpath. Please exclude <org.springframework.cloud:spring-cloud-sleuth-brave> dependency from <org.springframework.cloud:spring-cloud-starter-sleuth>.
```

**Sample**

Create a project on Spring Initializer with Spring Cloud Sleuth and configure according to the documentation. Here's a [sample](https://gist.github.com/nfrankel/e1522f4cb085c56199cc0a9610cbbc14)

After debugging, I found that a workaround is to set `spring.sleuth.otel.multiple-tracer-configs-detector-enabled=false`.

Still, if I exclude `spring-cloud-sleuth-brave`, the class should be absent from the classpath and the auto-configuration shouldn't kick in.

**Comment by jonatan-ivanov** [comment]
Thank you for the issue and for the reproducer!

[`MultipleTracerAutoConfigurationsDetector `](https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/blob/a054c61e9e80f4b018c57c230e55718eb59b4f78/spring-cloud-sleuth-otel-autoconfigure/src/main/java/org/springframework/cloud/sleuth/autoconfig/otel/MultipleTracerAutoConfigurationsDetector.java#L33) is really as simple as `@ConditionalOnClass(name = "brave.Tracer")` so there is a big chance that even if you exclude it from `spring-cloud-starter-sleuth`, something else brings it in.

If you look at the output of `./mvnw dependency:tree`, you can see something like this:
```
[INFO] +- org.mariadb:r2dbc-mariadb:jar:1.1.1-rc:runtime
[INFO] |  \- io.projectreactor.netty:reactor-netty:jar:1.0.21:runtime
[INFO] |     +- io.projectreactor.netty:reactor-netty-core:jar:1.0.21:compile
[INFO] |     |  +- io.netty:netty-handler:jar:4.1.79.Final:compile
[INFO] |     |  \- io.netty:netty-handler-proxy:jar:4.1.79.Final:compile
[INFO] |     |     \- io.netty:netty-codec-socks:jar:4.1.79.Final:compile
[INFO] |     +- io.projectreactor.netty.incubator:reactor-netty-incubator-quic:jar:0.0.10:runtime
[INFO] |     |  \- io.netty.incubator:netty-incubator-codec-native-quic:jar:linux-x86_64:0.0.28.Final:runtime
[INFO] |     |     \- io.netty.incubator:netty-incubator-codec-classes-quic:jar:0.0.28.Final:runtime
[INFO] |     |        \- commons-codec:commons-codec:jar:1.15:runtime
[INFO] |     \- io.projectreactor.netty:reactor-netty-http-brave:jar:1.0.21:runtime
[INFO] |        \- io.zipkin.brave:brave-instrumentation-http:jar:5.13.9:runtime
[INFO] |           \- io.zipkin.brave:brave:jar:5.13.9:runtime
```

Based on this, if I exclude `io.projectreactor.netty:reactor-netty-http-brave` from `org.mariadb:r2dbc-mariadb`, the app starts. Could you please check if doing this works for you?

This also means that the action item to resolve this in our error message is somewhat misleading since it does not cover the case when something else brings in Brave other than `spring-cloud-sleuth-brave`.

**Comment by jonatan-ivanov** [comment]
@violetagg Should not `reactor-netty-http-brave` be an optional dependency of `reactor-netty`?

**Comment by violetagg** [comment]
@jonatan-ivanov `reactor-netty` provides all modules provided by Reactor Netty (as an easy shortcut if you want everything). If one needs only some of them he/she can use Reactor Bom and then describe only those that are needed.

**Comment by nfrankel** [comment]
@jonatan-ivanov Indeed, with your workaround, it works 👍

**Comment by jonatan-ivanov** [comment]
@nfrankel Thanks, I'm going to improve the wording on the error message.

@violetagg Thanks, I'm going to let the `r2dbc-mariadb` maintainers know that they might have unwanted dependencies (in case they don't want a tracing lib by default).

**Comment by jonatan-ivanov** [comment]
Superseded by https://github.com/spring-projects-experimental/spring-cloud-sleuth-otel/issues/120
