### ISSUE TITLE
 spring-cloud-sleuth-otel officially in spring cloud

### ISSUE THREAD

**Issue by egridav** [spring-projects-experimental/spring-cloud-sleuth-otel#135]
Hi all,
pardon me, this is more a question than a request for feature.
Is there any plan to move 

**spring-projects-experimental/spring-cloud-sleuth-otel**

into an official release of spring cloud?

in other words...any chance this won't be experimental anymore?

Thanks a lot in advance for your help/info.

**Comment by marcingrzejszczak** [comment]
There's no plan to move it to the release train

**Comment by FWinkler79** [comment]
Thanks @marcingrzejszczak: is this just a temporary situation as in "no plans yet", or was it decided to not move it at all, as in "no plans ever"? It would be interesting for us, whether to continue into our current direction.

**Comment by jonatan-ivanov** [comment]
@FWinkler79 It is kind of like no plans ever since:
- OTel itself is not stable yet
  if you are not aware of this, check your classpath, you are consuming `-alpha` versions of OTel jars like [opentelemetry-semconv](https://search.maven.org/artifact/io.opentelemetry/opentelemetry-semconv) and [opentelemetry-instrumentation-api-semconv](https://search.maven.org/artifact/io.opentelemetry.instrumentation/opentelemetry-instrumentation-api-semconv)
- Sleuth will reach end of OSS support by 2023-05-18 (see [docs](https://spring.io/projects/spring-cloud-sleuth#support))
- There are not a lot of chance that OTel becomes stable by then

So the first thing I would consider if it is ok to use non-GA OTel jars. If so, it is probably ok to consume a GA Sleuth jar that is not part of the release train. If it is not ok for you to use non-GA OTel jars, you can continue using Sleuth with Brave.

You can also migrate to Micrometer Tracing and Spring Boot 3. You can find the migration guide here: https://github.com/micrometer-metrics/tracing/wiki/Spring-Cloud-Sleuth-3.1-Migration-Guide
